#server
server:
  port: 80
#datasource
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: wh990119
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mysql://42.193.20.105:3306/acg?serverTimezone=GMT%2B8
